name: Tests

on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    branches: main
    paths-ignore:
      - README.md

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.84.0
          components: clippy, rustfmt
      - uses: taiki-e/install-action@cargo-hack
      - uses: extractions/setup-just@v2
      - run: just check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.84.0
          components: clippy, rustfmt
      - uses: extractions/setup-just@v2
      - run: just test
